Repository react-native-community/hooks, pull requests merged in 2020-02, with the labels that each got.

#60 trying out auto
  .env.sample
  .gitignore
  .release-it.json
  CHANGELOG.md
  package.json
  yarn.lock
Labels: minor

#61 Update README.md
  README.md
Labels: patch

#63 try it
  .circleci/config.yml
Labels: minor, release

#64 hmmm
  package.json
  src/index.ts
Labels: minor

#69 hm
  package.json
Labels: patch

#70 ok
  src/index.ts
Labels: patch, release

#71 aha
  src/index.ts
Labels: patch, release

#72 upg
  yarn.lock
Labels: patch, release

#48 Improve unsubscription
  src/useKeyboard.ts
Labels: patch, release
